## Tutorial 12 Gradient Descent

In [8]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [84]:
df = pd.read_csv('tutorial12_insurance_data.csv')
df

,age,affordibility,bought_insurance
0,22,1,0
1,25,0,0
2,47,1,1
3,52,0,0
4,46,1,1
5,56,1,1
6,55,0,0
7,60,0,1
8,62,1,1
9,61,1,1


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age', 'affordibility']], df.bought_insurance, test_size=0.2, random_state=25)

In [11]:
len(X_train)

22

In [12]:
len(X_test)

6

In [13]:
X_train_scalled = X_train.copy()
X_train_scalled['age'] = X_train_scalled['age'] / 100

In [14]:
X_test_scalled = X_test.copy()
X_test_scalled['age'] = X_test_scalled['age'] / 100

In [15]:
X_train_scalled

,age,affordibility
0,0.22,1
13,0.29,0
6,0.55,0
17,0.58,1
24,0.50,1
19,0.18,1
25,0.54,1
16,0.25,0
20,0.21,1
3,0.52,0


In [16]:
X_test_scalled

,age,affordibility
2,0.47,1
10,0.18,1
21,0.26,0
11,0.28,1
14,0.49,1
9,0.61,1


In [17]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=((2,)), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

C:\Users\Dell-Precession\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [19]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(X_train_scalled, y_train, epochs=5000)

Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 766ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy

In [40]:
model.evaluate(X_test_scalled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.3550


[0.35497763752937317, 1.0]

In [41]:
model.predict(X_test_scalled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[0.70548475],
       [0.3556957 ],
       [0.16827832],
       [0.4780119 ],
       [0.72606957],
       [0.82949823]], dtype=float32)

In [42]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [43]:
coef, intercept = model.get_weights()
coef, intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

##### Coef is the one which which has w1 and w2 etc. And intercept is the bias

### Below we can see how we can add the same in plane python code

In [44]:
def sigmoid(x):
    import math
    return 1 / (1 + math.exp(-x))

In [45]:
sigmoid(18)

0.9999999847700205

In [46]:
sigmoid(0)

0.5

In [47]:
sigmoid(-5)

0.0066928509242848554

In [55]:
coef, intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

In [56]:
def predicted_function(age, affordability):
    weighted_sum = coef[0] * age + coef[1] * affordability + intercept
    return sigmoid(weighted_sum)

In [57]:
X_test_scalled

,age,affordibility
2,0.47,1
10,0.18,1
21,0.26,0
11,0.28,1
14,0.49,1
9,0.61,1


In [58]:
predicted_function(.47, 1)

C:\Users\Dell-Precession\AppData\Local\Temp\ipykernel_3580\3918314859.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.7054847702382996

In [60]:
predicted_function(.18, 1)

C:\Users\Dell-Precession\AppData\Local\Temp\ipykernel_3580\3918314859.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.35569571637887243

In [63]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

In [64]:
def sigmoid_numpy(X):
    return 1 / (1 + np.exp(-X))

In [66]:
sigmoid_numpy(np.array([12, 0, 1]))

array([0.99999386, 0.5       , 0.73105858])

In [79]:
def gradient_descent(age, affordability, y_true, epochs, loss_threshold):
    # we need to find w1, w2 and bias
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)

    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)
        w1d = (1/n)*np.dot(np.transpose(age), (y_predicted - y_true))
        w2d = (1/n)*np.dot(np.transpose(affordability), (y_predicted - y_true))
        bias_d = np.mean(y_predicted - y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d
        print(f'epoch:{i}, w1:{w1}, w2:{w2}, loss:{loss}')
        if loss <=loss_threshold:
            break
    return w1, w2, bias

In [80]:
X_train_scalled

,age,affordibility
0,0.22,1
13,0.29,0
6,0.55,0
17,0.58,1
24,0.50,1
19,0.18,1
25,0.54,1
16,0.25,0
20,0.21,1
3,0.52,0


In [81]:
gradient_descent(X_train_scalled['age'], X_train_scalled['affordibility'], y_train, 1000, 0.4631)

epoch:0, w1:0.974907633470177, w2:0.948348125394529, loss:0.7113403233723417
epoch:1, w1:0.9556229728273669, w2:0.9058873696677865, loss:0.681264778737757
epoch:2, w1:0.9416488476693794, w2:0.8719790823960313, loss:0.6591474252715025
epoch:3, w1:0.9323916996249162, w2:0.8457541517722915, loss:0.6431523291301917
epoch:4, w1:0.9272267472726993, w2:0.8262362885332687, loss:0.6316873063379158
epoch:5, w1:0.9255469396815343, w2:0.8124402814952774, loss:0.623471707997592
epoch:6, w1:0.9267936114129968, w2:0.8034375029757677, loss:0.6175321183044205
epoch:7, w1:0.93047170420295, w2:0.7983920007454487, loss:0.6131591858705934
epoch:8, w1:0.9361540784567942, w2:0.7965748796787705, loss:0.6098518179750948
epoch:9, w1:0.9434791243557357, w2:0.7973647616854131, loss:0.6072639970231438
epoch:10, w1:0.9521448361628082, w2:0.8002404280558159, loss:0.6051606942838051
epoch:11, w1:0.9619014360798376, w2:0.8047697991276092, loss:0.6033841405177724
epoch:12, w1:0.9725437902239876, w2:0.8105978078160995, 

(np.float64(5.051047623653049),
 np.float64(1.4569794548473887),
 np.float64(-2.9596534546250037))

In [82]:
coef, intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

##### We can see both results are near. Plan code and tensor flow gives same w1, w2 and bias