### Tutorial 11 : Loss and Cost functions

In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.3, 0.7, 1, 0, 0.5])

In [7]:
def mean_absolute_error(y_true, y_predicted):         # Function which explain how the mean absoulte error works
    total_errors = 0
    for yt, yp in zip(y_true, y_predicted):
        error = abs(yt - yp)
        print(error)
        total_errors = total_errors + error
    print("Total erros:" + str(total_errors))
    mean_absolute_error_value = total_errors / len(y_true)
    print("MAE:" + str(mean_absolute_error_value))
    return mean_absolute_error_value

In [8]:
mean_absolute_error(y_true, y_predicted)

0.7
0.30000000000000004
1.0
0.0
0.5
Total erros:2.5
MAE:0.5


np.float64(0.5)

In [9]:
np.abs(y_true - y_predicted)

array([0.7, 0.3, 1. , 0. , 0.5])

In [12]:
np.sum(np.abs(y_true - y_predicted))

np.float64(2.5)

In [20]:
np.mean(np.abs(y_true - y_predicted)) # Function which explain how the mean absoulte error works with powerful numpy with one line of code

np.float64(0.5)

#### Above is to understand how the mean absolute works

#### Below we can see how the log loss function (binary cross entorpy)

In [13]:
np.log([0.000000000000000001])

array([-41.44653167])

In [15]:
epsilon = 1e-15

In [16]:
epsilon

1e-15

In [17]:
y_predicted

array([1, 1, 0, 0, 1])

In [18]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [22]:
y_predicted_new = [min(i, 1 - epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [25]:
y_predicted_new = np.array(y_predicted_new)
y_predicted_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [26]:
-np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

np.float64(17.2696280766844)

In [27]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1 - epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

In [28]:
log_loss(y_true, y_predicted)

np.float64(17.2696280766844)