### Tutorial 10: Matrix

In [1]:
import numpy as np

In [2]:
revenue = np.array([[100, 120, 135], [40, 32, 34], [42, 55, 60]])
expense = np.array([[90, 96, 111], [20, 15, 23], [32, 40, 41]])

In [4]:
profit_and_loss = revenue - expense        # This is the power of numpy, we substract/add like this. it will do for matrix
profit_and_loss

array([[10, 24, 24],
       [20, 17, 11],
       [10, 15, 19]])

In [5]:
price = np.array([1000, 400, 1500])
units = np.array([[80, 94, 105], [40, 25, 15], [50, 60, 88]])

In [6]:
units_price = price * units

In [10]:
units_price

array([[ 80000,  37600, 157500],
       [ 40000,  10000,  22500],
       [ 50000,  24000, 132000]])

#### IT tool the same row and multipled. Above this method is called broadcasting. Meaning it is trying to match with bigger size array.
##### Here is it multiplying each with same price
##### When space of matrix is not same, it will expand and match with bigger. This is broadcasting. By default it will do this
##### In above even if you give same price with 2 more rows, it will give same result

### But we have to get the price for each year. Where we need to match with smaller size. Below is the code

In [12]:
price_of_units_in_each_years = np.dot(price, units)  # WE can use this dot function to do that
price_of_units_in_each_years

array([171000, 194000, 243000])

##### numpy has this dot method for using to calculate dot product