### Tutorial 10 : Matrix : Exercise

In [1]:
import numpy as np

In [9]:
revenue_in_dollars = np.array([[200, 220, 250], [68, 79, 105], [110, 140, 180], [80, 85, 90]])
india_rupees_for_a_dollar = np.array([75])

In [10]:
revenue_in_rupees = revenue_in_dollars * india_rupees_for_a_dollar
revenue_in_rupees

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [11]:
revenue_in_rupees_method2 = revenue_in_dollars * 75
revenue_in_rupees_method2

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [7]:
units_flowers_sold_in_each_months = np.array([[50, 60, 25], [10, 13, 5], [40, 70, 52]])
price_of_each_flower = np.array([20, 30, 15])

In [12]:
total_sold_each_months = np.dot(price_of_each_flower, units_flowers_sold_in_each_months)
total_sold_each_months

array([1900, 2640, 1430])